version: '3'

services:
  blogpy_postgresql:
    image: postgres:12
    container_name: blogpy_postgresql
    volumes: 
      - blogpy_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - 127.0.0.1:5000:80
    networks:
      - blogpy_network

volumes:
  blogpy_postgresql:
    external: true
networks:
  blogpy_network:
    external: true